name: PR

on:
  pull_request:

permissions:
  contents: write

jobs:
  pr:
    name: PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable && corepack prepare
      - uses: actions/setup-node@v3
        with:
          node-version-file: .node-version
          cache: pnpm

      - run: pnpm install

      - run: pnpm run build
      - run: pnpm run docs

      - uses: stefanzweifel/git-auto-commit-action@v4