name: PR

on:
  pull_request:

permissions:
  contents: write

jobs:
  pr:
    name: PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: corepack enable
      - uses: actions/setup-node@v2
        with:
          node-version-file: '.node-version'
          cache: 'pnpm'

      - run: pnpm install
      - run: pnpm build
      - run: pnpm run docs

      - uses: stefanzweifel/git-auto-commit-action@v4