name: Release

on:
  push:
    branches: ['main']

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: corepack enable && corepack prepare
      - uses: actions/setup-node@v3
        with:
          node-version-file: .node-version
          cache: yarn

      - run: yarn install
      - run: yarn build

      - uses: changesets/action@v1
        with:
          publish: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}